openapi: 3.0.4
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.12
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about

tags:
  - name: pet
    description: Everything about your Pets

paths:
  /api/v1/pet/{petId}:
    $ref: ./paths/pet_by_id.yaml
